[tool.poetry]
name = "testhwmd"
version = "0.1.0"
description = "\\"
authors = ["Danila Makarov <57109784+dqnilka@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
